# Simple Julia  🚀
________

## Table of Contents:
* [Commenting](#Commenting)
* [Print Statements](#Print_statements)
* [Object Types](#Object_types)
* [Arithmetic Operations](#Arithmetic_Operations)
* [Strings](#Strings)
* [Characters](#Characters)
* [Dictionaries](#Dictionaries)
* [Tuples](#Tuples)
* [Arrays](#Arrays)
* [While Loops](#While_loops)
* [For Loops](#For_loops)
* [Conditionals](#Conditionals)


<a class="anchor" id="Commenting"></a>
# Commenting

In [167]:
# Single line comment

#= 
Multi-line
comments
are 
fun 
=#

<a class="anchor" id="Print_statements"></a>
# Print Statements


In [48]:
println("A simple guide to Julia")
println("""A simple guide to "Julia" """)

first_name="Hillary "; last_name="Scannell"
years=10; decades=3

println("My name is $(string(first_name,last_name)).")
println("I am $(years*decades) years old.")


A simple guide to Julia
A simple guide to "Julia" 
My name is Hillary Scannell.
I am 30 years old.


<a class="Object types" id="Object_types"></a>
# Object Types

In [25]:
println(typeof('a'))
println(typeof(1))
println(typeof(1.5))
println(typeof((1,2)))
println(typeof((1,2.5)))
println(typeof((1,'a')))

Char
Int64
Float64
Tuple{Int64, Int64}
Tuple{Int64, Float64}
Tuple{Int64, Char}


<a class="Arithmetic Operations" id="Arithmetic_Operations"></a>
# Arithmetic Operations

In [37]:
sum = 1 + 2
difference = 2 - 1
product = 2 * 2
quotient = 10 / 2
power = 10 ^ 2
modulus = 11 % 2 ; # supress output with ;

<a class="Strings" id="Strings"></a>
# Strings

In [71]:
# Assignment

str1 = "But I want "
str2 = """more.""";

In [72]:
# Concatenation

println(string("I have ", 12, " apples."))
println(str1*str2)
println("$str1$str2")

I have 12 apples.
But I want more.
But I want more.


<a class="Characters" id="Characters"></a>
# Characters

In [39]:
char = 'a'
typeof(char)

Char

<a class="Dictionaries" id="Dictionaries"></a>
# Dictionaries
- Not ordered
- Cannot index a dictionary
- Mutable: can update contents after they are diclared

In [75]:
age = Dict("Hillary" => 30, "John" => 40, "Sally" => 22)

Dict{String, Int64} with 3 entries:
  "Hillary" => 30
  "Sally"   => 22
  "John"    => 40

In [107]:
# update and add to dictionary
age["Sally"] = 23
age["Mark"] = 29
age

Dict{String, Int64} with 4 entries:
  "Hillary" => 30
  "Sally"   => 23
  "Mark"    => 29
  "John"    => 40

In [108]:
println("Hillary is $(age["Hillary"]) years old.")

Hillary is 30 years old.


In [109]:
# delete a key from the dictionary
pop!(age, "Mark")
age

Dict{String, Int64} with 3 entries:
  "Hillary" => 30
  "Sally"   => 23
  "John"    => 40

In [110]:
# merge two dictionaries
merge!(age, Dict("Mark" => 29))



Dict{String, Int64} with 4 entries:
  "Hillary" => 30
  "Sally"   => 23
  "Mark"    => 29
  "John"    => 40

In [112]:
# index into dictionary
age["Sally"]

23

<a class="Tuples" id="Tuples"></a>
# Tuples
- Ordered sequences of elements
- Can index tuples
- Immutable

In [113]:
forecast = ("sun", "clouds", "rain")

("sun", "clouds", "rain")

In [114]:
# indexing starts at 1
forecast[1]

"sun"

<a class="Arrays" id="Arrays"></a>
# Arrays
- Ordered sequences of elements
- Mutable

In [115]:
# array of strings
countries = ["France", "Italy", "Australia", "Japan"]

4-element Vector{String}:
 "France"
 "Italy"
 "Australia"
 "Japan"

In [126]:
# array of integers
pi = [3, 1, 4, 1, 5, 9]

6-element Vector{Int64}:
 3
 1
 4
 1
 5
 9

In [138]:
pi = ["pi", 3, 3.14159]

3-element Vector{Any}:
  "pi"
 3
 3.14159

In [139]:
# Indexing arrays, starts at 1
pi[1]
pi

3-element Vector{Any}:
  "pi"
 3
 3.14159

In [140]:
# reassign elements in array
pi[1] = "Archimedes"
pi

3-element Vector{Any}:
  "Archimedes"
 3
 3.14159

In [141]:
# add element to array
push!(pi, 3.14)
pi

4-element Vector{Any}:
  "Archimedes"
 3
 3.14159
 3.14

In [142]:
# remove element from array
pop!(pi)
pi

3-element Vector{Any}:
  "Archimedes"
 3
 3.14159

**Nd arrays**

In [144]:
array = [[countries, pi]]

1-element Vector{Vector{Vector{Any}}}:
 [["France", "Italy", "Australia", "Japan"], ["Archimedes", 3, 3.14159]]

In [145]:
# arrays can be variable length
numbers = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

In [146]:
# create a random 2D array with numbers between 0 and 1
rand(4, 3)

4×3 Matrix{Float64}:
 0.330353  0.759646  0.709709
 0.769819  0.428513  0.170475
 0.250828  0.686283  0.0111661
 0.739677  0.885282  0.606127

In [148]:
# create a random 3D array
rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.584802   0.889698  0.926713
 0.555925   0.651377  0.259384
 0.458073   0.113136  0.742791
 0.0769394  0.936436  0.735673

[:, :, 2] =
 0.796518  0.251318  0.00684245
 0.612246  0.37331   0.946431
 0.682343  0.718011  0.637061
 0.639556  0.251649  0.305485

<a class="While loops" id="While_loops"></a>
# While loops

```julia
while *condition*
    *loop body*
end
```

In [149]:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [153]:
i = 1
while i <= length(countries)
    country = countries[i]
    println(country)
    i += 1
end

France
Italy
Australia
Japan


<a class="For loops" id="For_loops"></a>
# For loops

```julia
for *var* in *loop iterable*
    *loop body*
end
```

In [157]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [159]:
for n = 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [160]:
for n ∈ 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [158]:
for country in countries
    println(country)
end

France
Italy
Australia
Japan


In [162]:
# initialize an array with zeros
m, n = 5, 5
A = zeros(m, n)

# value of every entry is the sum of its rows and column indices
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [163]:
# Alternatively
B = zeros(m, n)

for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [165]:
# Array comprehension
# Don't need to initialize C
C = [i + j for i in 1:m, j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [166]:
# Watch the tables grow in size
for n in 1:10
    A = [i + j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Matrix{Int64}:
 2

2×2 Matrix{Int64}:
 2  3
 3  4

3×3 Matrix{Int64}:
 2  3  4
 3  4  5
 4  5  6

4×4 Matrix{Int64}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Matrix{Int64}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Matrix{Int64}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Matrix{Int64}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Matrix{Int64}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

<a class="Conditionals" id="Conditionals"></a>
# Conditionals

```julia
if *condition 1*
    *option 1*
elseif *condition 2*
    *option 2*
else
    *option 3*
end
```